# Codecov configuration file
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 50%
        threshold: 5%
        base: auto
    patch:
      default:
        target: 50%
        threshold: 5%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "tests/"
  - "test_*.py"
  - "**/test_*.py"
  - "**/*_test.py"
  - "**/__pycache__/"
  - "**/.venv/"
  - "**/venv/"
  - "**/env/"
  - "**/.env/"
  - "**/node_modules/"
  - "**/coverage/"
  - "**/.coverage"
  - "**/htmlcov/"
  - "**/.pytest_cache/"
  - "**/.git/"
  - "**/Dockerfile*"
  - "**/docker-compose*.yml"
  - "**/Makefile"
  - "**/README.md"
  - "**/*.md"
  - "**/*.txt"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.json"
  - "**/*.ini"
  - "**/*.cfg"
  - "**/*.toml"
  - "**/*.lock"
  - "**/requirements*.txt"
  - "**/setup.py"
  - "**/setup.cfg"
  - "**/pyproject.toml"
  - "**/MANIFEST.in"
  - "**/.gitignore"
  - "**/.gitattributes"
  - "**/.editorconfig"
  - "**/.pre-commit-config.yaml"
  - "**/.github/"
  - "**/.vscode/"
  - "**/.idea/"
  - "**/*.log"
  - "**/*.tmp"
  - "**/*.bak"
  - "**/*.swp"
  - "**/*.swo"
  - "**/*~"
  - "**/#*#"
  - "**/.#*"
  - "**/._*"
  - "**/Thumbs.db"
  - "**/.DS_Store"
  - "**/ehthumbs.db"
  - "**/Desktop.ini"

github_checks:
  annotations: yes 