services:
  app:
    build:
      context: ./startrek-rag
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./startrek-rag/_temp:/app/_temp
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - OLLAMA_HOST=host.docker.internal
      - LLM_MODEL=deepseek-r1:1.5b
    depends_on:
      - chroma
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  chroma:
    image: chromadb/chroma:${CHROMA_VERSION:-0.4.24}
    volumes:
      - ./chroma-data:/chroma/chroma
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 