version: '3.8'

services:
  app:
    build:
      context: ./startrek-rag
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./chroma-data:/app/chroma-data
      - ./startrek-rag/_temp:/app/_temp
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - OLLAMA_HOST=host.docker.internal
      - LLM_MODEL=llama3.2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - chroma
    networks:
      - app-network

  chroma:
    image: chromadb/chroma:0.4.24
    volumes:
      - ./chroma-data:/chroma/chroma
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  app-network:
    driver: bridge 