name: Test Only

on:
  push:
    branches: ["*", "!gh-pages"]
  pull_request:
    branches: ["*", "!gh-pages"]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      chroma:
        image: chromadb/chroma:latest
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -f http://localhost:8000/api/v1/heartbeat"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        pip install -r startrek-rag/requirements.txt
        pip install -r content_loader/requirements.txt
        
    - name: Run unit tests
      run: |
        pytest tests/unit/ -v --cov=startrek-rag --cov=content_loader --cov-report=xml --cov-report=html
        
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v --cov=startrek-rag --cov=content_loader --cov-report=xml --cov-report=html
        
    - name: Run all tests with coverage
      run: |
        pytest tests/ -v --cov=startrek-rag --cov=content_loader --cov-report=xml --cov-report=html --cov-report=term-missing
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        
    - name: Upload coverage HTML
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html
        path: htmlcov/
        retention-days: 30 